# Generated by Django 4.0.5 on 2023-02-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_component', '0002_rename_description_event_details_event_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Booking',
        ),
    ]
