# Generated by Django 4.1.7 on 2023-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_component', '0007_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='materials_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quote',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
