# Generated by Django 4.1.7 on 2023-03-13 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_component', '0012_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
