# Generated by Django 4.1.7 on 2023-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_component', '0002_inventory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
